services:

  backend:
    build: ./backend
    container_name: pps-backend
    ports:
      - "5001:5001"
    volumes:
      - db_data:/app/instance
    environment:
      - JWT_SECRET=super_secret_key
    restart: always

  frontend:
    build: ./frontend
    container_name: pps-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: